name: Daily Build Components
on:
  workflow_call:
  workflow_dispatch:

jobs:

  pushChecker:
    name: Daily Interlisp Push Check and Build
    runs-on: ubuntu-latest
    outputs:
      desiredTag: ${{ steps.currentName.outputs.medley }}
      cacheHit: ${{ steps.checkSha.outputs.cache-hit }}
      latestTag: ${{ steps.latestMedleyVersion.outputs.latest_tag }}

    steps:
      - name:  Create cache file
        run: |
          mkdir check-SHA
          echo ${{ github.sha }} > github-sha.txt

      - name: Check SHA
        id: checkSha
        uses: actions/cache@v2.1.7
        with:
          path: check-SHA
          key: check-SHA-$${{ github.sha }}

      # Get Medley release information, retrieves the name of the latest
      # release. 
      - name: Get Medley Release Information
        id: latestMedleyVersion
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: Interlisp
          repo: medley

      - name: Get current Release Name
        id: currentName
        run: |
          echo "Execute additional steps"
          echo ::set-output name=medley::"medley-`date +%y%m%d`"
          echo "Latest Tag ${{ steps.latestMedleyVersion.outputs.latest_tag }}"

#  check_if_build_needed:
#    needs: push_checker     
#    runs-on: ubuntu-latest
#    steps:
#      - uses: build_medley

  do_build_medley:
    needs: pushChecker
    runs-on: ubuntu-latest
    # uses: stumbo/medley/.github/workflows/buildLoadup.yml@master
    if: !( needs.push_checker.outputs.cache_hit ) &&  ( needs.push_checker.outputs.latest_tag !=  needs.push_checker.outputs.desired_tag )
    steps:
     - name: do work
       run: |
        echo "Cache Hit: " ${{ needs.pushChecker.outputs.cacheHit }} 
        echo "Desired Tag: " ${{ needs.pushChecker.outputs.desiredTag }}
        echo "Latest Tag: " ${{ needs.pushChecker.outputs.latestTag }}