name: Interlisp Toolset Daily Build Action
# Run daily at 0200 hrs
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  push_checker:
    name: Daily Interlisp Push Check and Build
    runs-on: ubuntu-latest
    outputs:
      desired_tag: ${{ steps.current_name.outputs.medley }}
      cache_hit: ${{ steps.check_sha.outputs.cache-hit }}
      latest_tag: ${{ steps.latest_medley_version.outputs.latest_tag }}
    steps:
      - name:  Create cache file
        run: |
          mkdir check-SHA
          echo ${{ github.sha }} > github-sha.txt

      - name: Check SHA
        id: check_sha
        uses: actions/cache@v2.1.7
        with:
          path: check-SHA
          key: check-SHA-$${{ github.sha }}

      # Get Medley release information, retrieves the name of the latest
      # release. 
      - name: Get Medley Release Information
        id: latest_medley_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: Interlisp
          repo: medley

      - name: Get current Release Name
        id: current_name
        run: |
          echo "Execute additional steps"
          echo "medley-`date +%y%m%d`" >> $GITHUB_ENV
          echo ::set-output name=medley::{{ $GITHUB_ENV }}

  build_medley:
    needs: push_checker
    runs-on: ubuntu-latest
    if: push_checker.outputs.cache_hit != 'true' # &&  push_checker.outputs.latest_tag != push_checker.outputs.desired_tag
    uses: stumbo/medley/.github/workflows/buildLoadup@master

