name: Interlisp Toolset Daily Build Action
# Run daily at 0200 hrs
on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  push_checker:
    name: Daily Interlisp Push Check and Build
    runs-on: ubuntu-latest
    steps:
      - name:  Create cache file
        run: |
          mkdir check-SHA
          echo ${{ github.sha }} > github-sha.txt

      - name: Check SHA
        id: check_sha
        uses: actions/cache@v2.17
        with:
          path: check-SHA
          key: check-SHA-$${{ github.sha }}

      - name: Build Medley
        if: steps.check_sha.output.cache-hit != 'true'
        run: echo "Execute additional steps"
