name: Interlisp Toolset Daily Build Action
# Run daily at 0200 hrs
on:
#  schedule:
#    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:

  build_maiko:
    name: Build Maiko Release Package
    runs-on: ubuntu-latest
    steps:
      - name: do something
        run: echo "Build Maiko"
  
  build_medley:
    name: Build Medley Loadups
    runs-on: ubuntu-latest
    needs: build_maiko
    steps:
      - name: Build Medley
        id: daily_medley_build
        uses: stumbo/medley/.github/workflows/action@v0.11
      - run: echo "Medley Build Complete"

  build_docker_container:
    name: Build the Medley docker container
    runs-on: ubuntu-latest
    needs: build_medley
    steps:
      - name: do something
        run: echo "Build Docker Container"

  build_online_medley:
    name: Build the online Medley system
    runs-on: ubuntu-latest
    needs: build_docker_container
    steps:
      - name: do something
        run: echo "Build Online Medley System"
